config/routes.rb
Blog::Application.routes.draw do
  resources :users
  match 'login'         => 'users#login'
  get 'logout'          => 'users#logout'
  get 'confirm/:token'  => 'users#confirm'
  
  resources :posts do
    member do
      post :create_comment
      delete 'destroy_comment/:id' => 'posts#destroy_comment', as: 'destroy_comment'
    end
  end
  
  get 'archive' => 'posts#full_archive', as: 'full_archive'
  get 'archive/:year/:month' => 'posts#archive', constraints: { year: /\d{4}/, month: /\d{1,2}/ }, as: 'archive'
  
  get 'contacts' => 'static_pages#contacts'
  get 'about'    => 'static_pages#about'
  
  root :to => 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :author, :class_name => 'User'
  has_ancestry
  
  validates_presence_of :content
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_links(comment)
    links = [] << link_to(
      t('posts.show.reply'),
      '#',
      id: "reply_link_#{comment.id}",
      class: 'reply_link'
    )
    
    links << link_to(
      t('common.delete'),
      destroy_comment_post_path(comment),
      :method => :delete,
      confirm: t('common.confirm_delete')
    ) if can? :delete, comment
    
    links.join(' ').html_safe
  end
end

app/views/comments/_comment.html.erb
<article class="comment">
  <header>
    <%= link_to comment.author.name, comment.author %> @
    <%= format_date(comment.created_at) %>
  </header>
  
  <%= textilize(comment.content) %>
  
  <footer>
    <% if can? :create, Comment %>
      <%= comment_links(comment) %>
      
      <div style="display:none;" class="reply_form" id="reply_form_<%= comment.id %>">
        <%= render 'comments/form', :comment => Comment.new(:parent_id => comment.id) %>
      </div>
    <% end %>
  </footer>
</article>

app/views/comments/_form.html.erb
<%= form_for comment, :url => create_comment_post_path(@post) do |f| %>
  <%= f.hidden_field :parent_id %>
  <%= f.text_area :content, :rows => 3 %><br />
  <%= f.submit 'Отправить' %>
<% end %>