config/routes.rb
Blog::Application.routes.draw do
  resources :users
  match 'login'         => 'users#login'
  get 'logout'          => 'users#logout'
  get 'confirm/:token'  => 'users#confirm'
  
  resources :posts do
    member do
      post :create_comment
      delete 'destroy_comment/:id' => 'posts#destroy_comment', as: 'destroy_comment'
    end
  end
  
  get 'archive' => 'posts#full_archive', as: 'full_archive'
  get 'archive/:year/:month' => 'posts#archive', constraints: { year: /\d{4}/, month: /\d{1,2}/ }, as: 'archive'
  
  get 'contacts' => 'static_pages#contacts'
  get 'about'    => 'static_pages#about'
  
  root :to => 'posts#index'
end

app/views/shared/_auth.html.erb
<div id="auth">
  <% if logged_in? %>
    <%= t('layout.welcome') %>
    <%= link_to(current_user.name, current_user) %> |
    <%= link_to t('layout.logout'), logout_path %>
  <% else %>
    <%= link_to t('layout.login'), login_path %> |
    <%= link_to t('layout.register'), new_user_path %>
  <% end %>
</div>

app/views/shared/_ga.html.erb
<script type="text/javascript">
  
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24065755-1']);
  _gaq.push(['_trackPageview']);
  
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  
</script>