config/routes.rb
Blog::Application.routes.draw do
  resources :users
  match 'login'         => 'users#login'
  get 'logout'          => 'users#logout'
  get 'confirm/:token'  => 'users#confirm'
  
  resources :posts do
    member do
      post :create_comment
      delete 'destroy_comment/:id' => 'posts#destroy_comment', as: 'destroy_comment'
    end
  end
  
  get 'archive' => 'posts#full_archive', as: 'full_archive'
  get 'archive/:year/:month' => 'posts#archive', constraints: { year: /\d{4}/, month: /\d{1,2}/ }, as: 'archive'
  
  get 'contacts' => 'static_pages#contacts'
  get 'about'    => 'static_pages#about'
  
  root :to => 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :author, :class_name => 'User'
  
  validates_presence_of :title, :body
  
  START_MONTH = 201106
  CUT_TAG = /<cut[^>]*>/
  
  before_save :make_preview
  default_scope order('id DESC')
  
  scope :created_on, lambda { |year, month|
    year, month = year.to_i, month.to_i
    start = Date.new(year, month, 1)
    stop  = Date.new(year, month, -1)
    date_range = (start..stop)
    where(created_at: date_range)
  }
  
  def self.archive_monthes
    years = {}
    (START_MONTH..Time.now.strftime('%Y%m').to_i).each do |month_num|
      month_string = month_num.to_s
      year, month = month_string[0..3], month_string[4..5]
      (years[year.to_i] ||= []) << month.to_i if created_on(year, month).count > 0
    end
    years
  end
  
  def has_comments?
    comments.size > 0
  end
  
  def make_preview
    match = CUT_TAG.match(self.body)
    self.preview = match ? match.pre_match : self.body
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  authorize_resource :except => [:create_comment, :destroy_comment, :archive, :full_archive]
  
  # GET /posts
  # GET /posts.xml
  def index
    @posts = Post.includes(:comments, :author)
    @years = Post.archive_monthes
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end
  
  def archive
    @posts = Post.includes(:comments, :author).created_on(params[:year], params[:month])
    @years = Post.archive_monthes
    authorize! :read, Post
    
    render 'index'
  end
  
  def full_archive
    @years = Post.archive_monthes
    authorize! :read, Post
  end
  
  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end
  
  def create_comment
    authorize! :create, Comment
    @post = Post.find(params[:id])
    comment = Comment.create params[:comment].merge(author: current_user)
    @post.comments << comment
    redirect_to @post
  end
  
  def destroy_comment
    @comment = Comment.find(params[:id])
    authorize! :delete, @comment
    post = @comment.post
    @comment.destroy
    redirect_to post, notice: t('posts.show.comment_deleted')
  end
  
  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end
  
  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end
  
  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new params[:post].merge(:author => current_user)
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => t('posts.show.post_created')) }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])
    
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => t('posts.show.post_updated')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to(posts_url, notice: t('posts.index.post_deleted')) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def format_date(date)
    content_tag 'time', :datetime => date.strftime('%Y-%m-%dT%H:%M') do
      date.strftime('%Y.%m.%d | %H:%M')
    end
  end
  
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), :class => "nested_comments")
    end.join.html_safe
  end
  
  def post_links(post)
    links = [] << link_to(
      t('posts.common.to_index'),
      posts_path
    )
    
    links << link_to(
      t('common.edit'),
      edit_post_path(@post)
    ) if can? :update, @post
    
    links << link_to(
      t('common.delete'),
      @post,
      method: :delete,
      confirm: t('common.confirm_delete')
    ) if can? :delete, @post
    
    links.join(' | ').html_safe
  end
end

app/views/posts/_archive.html.erb
<h3>Архив</h3>
<ul>
  <% @years.each do |year, monthes| %>
    <% monthes.each do |month| %>
      <li><%= link_to t("monthes.m#{month}") + " #{year}", archive_path(:year => year, :month => month) %></li>
    <% end %>
  <% end %>
</ul>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.input :title, autofocus: true %>
  <%= f.input :body %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<section id="post">
  <h1><%= t('posts.edit.header') %></h1>
  
  <%= render 'form' %>
  
  <p class="links">
    <%= link_to t('posts.common.to_index'), posts_path %> |
    <%= link_to t('common.show'), @post %>
  </p>
</section>

app/views/posts/full_archive.html.erb
<section id="archive">
  <%= render 'archive' %>
</section>

app/views/posts/index.html.erb
<section id="posts">
<% @posts.each do |post| %>
  <article class="post">
    <header>
      <h2><%= post.title %></h2>
      <p>
        <%= link_to post.author.name, post.author %> @
        <%= format_date(post.created_at) %>
      </p>
    </header>
    <%= textilize(post.preview) %>
    <footer>
      <p><%= link_to t(:comments, :count => post.comments.size), post_path(post) %></p>
    </footer>
  </article>
<% end %>
  <footer id="posts_footer">
    <%= link_to t('posts.index.new'), new_post_path if can? :create, Post %>
  </footer>
</section>

<section id="sidebar">
  <nav>
    <%= render 'archive' %>
  </nav>
</section>

<div style="clear:both;"></div>

app/views/posts/new.html.erb
<section id="post">
  <h1><%= t('posts.new.header') %></h1>
  
  <%= render 'form' %>
  
  <p class="links">
    <%= link_to t('posts.common.to_index'), posts_path %>
  </p>
</section>

app/views/posts/show.html.erb
<section id="post">
  <article>
    <header>
      <h2><%= @post.title %></h2>
      <p>
        <%= link_to @post.author.name, @post.author %> @
        <%= format_date(@post.created_at) %>
      </p>
    </header>
    
    <%= textilize(@post.body) %>
  </article>
</section>

<section id="comments">
  <% if @post.has_comments? %>
    <h3><%= t('posts.show.comments') %></h3>
    <%= nested_comments @post.comments.arrange(:order => :created_at) %>
  <% else %>
    <span class="no_comments"><%= t('posts.show.no_comments') %></span>
  <% end %>
  
  <% if can? :create, Comment %>
    <h3><%= t('posts.show.new_comment') %></h3>
    <%= render 'comments/form', :comment => Comment.new %>
  <% end %>
</section>

<p class="links">
  <%= post_links(@post) %>
</p>